repos:
-   repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.8.0
    hooks:
    -   id: pre-commit-update
        args:
        -   --verbose
-   repo: https://github.com/commitizen-tools/commitizen
    rev: v4.9.1
    hooks:
    -   id: commitizen
    -   id: commitizen-branch
        stages:
        -   pre-push
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
        exclude_types: [svg]
    -   id: check-yaml
    -   id: check-json
    -   id: check-xml
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.13.2
    hooks:
    -   id: ruff
        args:
        -   --fix
        -   --exit-non-zero-on-fix
        types_or: [python, pyi, jupyter]
    -   id: ruff-format
        types_or: [python, pyi, jupyter]
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.18.2
    hooks:
    -   id: mypy
        language_version: python3.11
        args:
        -   --config-file=pyproject.toml
        -   --ignore-missing-imports
        additional_dependencies:
        -   types-pytz
        -   types-python-dateutil
        exclude: "scratch"
-   repo: https://github.com/jsh9/pydoclint
    rev: 0.7.3
    hooks:
    -   id: pydoclint
